### ISSUE TITLE
Is this being maintained anymore?

### ISSUE THREAD

**Issue by admmasters** [FormidableLabs/whackage#15]
Hi Guys,

Thanks for the work for this tool - are you planning on maintaining it - or is it not something you are using internally anymore? I don't mind taking it over if not - I've got a fork: https://github.com/admmasters/whackage and it works with the latest react-native. I'll create a PR anyway to fix.

Ta

Matt

**Comment by ryan-roemer** [comment]
@admmasters -- Yep! @jevakallio has been on holiday for a while and is due back in town next week. Thanks for your PR and we'll hopefully pick that one up after Jani's back.
