### ISSUE TITLE
Switch to all async I/O.

### ISSUE THREAD

**Issue by ryan-roemer** [FormidableLabs/whackage#3]
Not sure how many files / dirs total will be watched / processed, but if it's a sizeable number the sync I/O is going to catch up with us. E.g., things in https://github.com/FormidableLabs/whackage/search?utf8=%E2%9C%93&q=fs+AND+sync&type=Code like `fs.writeFileSync` and `fs.existsSync` should be converted to their async counterparts.

Fortunately for control flow we have `Promise` already given we're node 4+...

**Comment by jevakallio** [comment]
@ryan-roemer sync IO is used only to read/write the config file and to assert the existence of config files.

All "serious" file copying is already done async. It's a tradeoff to achieve super simple control flow when initializing the tasks.

Closing as `wont-fix` 😜

**Comment by ryan-roemer** [comment]
Ah, yeah config file-only is a valid sync thing that doesn't have a scale concern.
