### ISSUE TITLE
Overrides local rn-cli.config.js

### ISSUE THREAD

**Issue by parshap** [FormidableLabs/whackage#7]
When using `whack run start` local configuration in my `rn-cli.config.js` is not applied. It looks like the `--config` argument is passed to the packager, which causes it to use *only* that config file. It would be nice if the two configs were merged somehow.

**Comment by jevakallio** [comment]
Thanks! Good idea. I didn't have need for this in my own projects so didn't build it in.

Can you test if the changes in https://github.com/FormidableLabs/whackage/pull/8 work for your use case? Please check the PR description for how it works and how to test it.

**Comment by jevakallio** [comment]
Released as [v1.1.0](https://github.com/FormidableLabs/whackage/releases/tag/v1.1.0)! 🎉
